local fs=require("filesystem")
local function r(name)
	if fs.exists(name) then
		print("removing "..name)
		fs.remove(name)
	end
end
print("uninstalling MCNnet2")
r("/etc/mnp")
r("/etc/mnpSavedNetworks.st")
r("/etc/mnpSavedDomains.st")
r("/etc/mnpSavedRoutes.st")

r("/usr/lib/cmnp.lua")
r("/usr/lib/ftp.lua")
r("/usr/lib/ssap.lua")
r("/usr/lib/ipv2.lua")
r("/usr/lib/netpacket.lua")
r("/usr/lib/wdp.lua")
r("/usr/lib/apm-lib.lua")
r("/usr/lib/tdf.lua")
r("/lib/cmnp.lua")
r("/lib/ftp.lua")
r("/lib/ssap.lua")
r("/lib/ipv2.lua")
r("/lib/netpacket.lua")

r("/usr/bin/cm.lua")
r("/usr/bin/nadm.lua")
r("/usr/bin/ssapClient.lua")
r("/usr/bin/ssapServer.lua")
r("/usr/bin/ftp-get.lua")
r("/usr/bin/ftp-put.lua")
r("/usr/bin/ftpServer.lua")
r("/usr/bin/wb.lua")
r("/usr/bin/tdfview.lua")

r("/bin/cm.lua")
r("/bin/ssapClient.lua")
r("/bin/ssapServer.lua")
r("/bin/ftp-get.lua")
r("/bin/ftp-put.lua")
r("/bin/ftpServer.lua")